# Generated by Django 3.2.9 on 2021-12-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='Username',
        ),
        migrations.AddField(
            model_name='newuser',
            name='FName',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='newuser',
            name='LName',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='newuser',
            name='RPwd',
            field=models.CharField(default='', max_length=150),
        ),
    ]
