# Generated by Django 3.2.9 on 2021-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0002_auto_20211205_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=150)),
                ('CNum', models.IntegerField()),
                ('Expm', models.DateField()),
                ('Expy', models.DateField()),
                ('CVV', models.IntegerField()),
                ('Tbill', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='newuser',
            name='FName',
            field=models.CharField(max_length=150),
        ),
    ]
