# Generated by Django 3.2.9 on 2021-12-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0003_auto_20211205_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Expm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Expy',
            field=models.IntegerField(),
        ),
    ]
