# Generated by Django 3.2.9 on 2021-12-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0004_auto_20211205_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=150)),
                ('Lastname', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Pass', models.CharField(max_length=150)),
                ('Rpass', models.CharField(max_length=150)),
            ],
        ),
    ]
