# Generated by Django 3.2.9 on 2021-12-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0005_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='Rpass',
            new_name='Repass',
        ),
    ]
