# Generated by Django 3.2.9 on 2021-12-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0007_newuser_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='Residence',
            field=models.CharField(default='', max_length=150),
        ),
    ]
